version: "3.7"

services:
  webapp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecoding-nodejs-server
    container_name: ecoding-nodejs-server
    volumes:
      - .:/ecoding/ecoding-nodejs-server
      - /ecoding/ecoding-nodejs-server/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
  mongo:
    image: mongo
    container_name: ecoding-server-mongodb
    ports:
      - "27017:27017"
